import 'package:flutter/widgets.dart';
import 'package:lucide_icons_flutter/lucide_icons.dart';

class TonztoonIcons {
  const TonztoonIcons._();

  static const IconData accountCircle = LucideIcons.circleUserRound;
  static const IconData alternateEmail = LucideIcons.atSign;
  static const IconData arrowBack = LucideIcons.arrowLeft;
  static const IconData apple = LucideIcons.apple;
  static const IconData autoAwesome = LucideIcons.sparkles;
  static const IconData autoStories = LucideIcons.bookOpen;
  static const IconData autoStoriesRounded = LucideIcons.bookOpenText;
  static const IconData bookMarked = LucideIcons.bookMarked;
  static const IconData bookOpenCheck = LucideIcons.bookOpenCheck;
  static const IconData bell = LucideIcons.bell;
  static const IconData badge = LucideIcons.badge;
  static const IconData bookmark = LucideIcons.bookmark;
  static const IconData bookmarkAdded = LucideIcons.bookmarkCheck;
  static const IconData bookmarkRounded = LucideIcons.bookmarkCheck;
  static const IconData cancel = LucideIcons.circleX;
  static const IconData check = LucideIcons.check;
  static const IconData chevronRight = LucideIcons.chevronRight;
  static const IconData cleaningServices = LucideIcons.brushCleaning;
  static const IconData close = LucideIcons.x;
  static const IconData cloudOff = LucideIcons.cloudOff;
  static const IconData contrast = LucideIcons.contrast;
  static const IconData createNewFolder = LucideIcons.folderPlus;
  static const IconData darkMode = LucideIcons.moon;
  static const IconData deleteOutline = LucideIcons.trash2;
  static const IconData deleteSweep = LucideIcons.trash2;
  static const IconData devices = LucideIcons.monitorSmartphone;
  static const IconData download = LucideIcons.download;
  static const IconData eye = LucideIcons.eye;
  static const IconData eyeOff = LucideIcons.eyeOff;
  static const IconData folder = LucideIcons.folder;
  static const IconData folderCopy = LucideIcons.folderOpen;
  static const IconData gMobiledata = LucideIcons.badgeCheck;
  static const IconData gift = LucideIcons.gift;
  static const IconData history = LucideIcons.history;
  static const IconData home = LucideIcons.house;
  static const IconData keyboardArrowDown = LucideIcons.chevronDown;
  static const IconData library = LucideIcons.library;
  static const IconData libraryBooks = LucideIcons.libraryBig;
  static const IconData messageSquare = LucideIcons.messageSquare;
  static const IconData lightMode = LucideIcons.sun;
  static const IconData localFireDepartment = LucideIcons.flame;
  static const IconData lockOutline = LucideIcons.lock;
  static const IconData login = LucideIcons.logIn;
  static const IconData logout = LucideIcons.logOut;
  static const IconData manageSearch = LucideIcons.searchCheck;
  static const IconData mapPin = LucideIcons.mapPin;
  static const IconData menuBook = LucideIcons.bookOpen;
  static const IconData moreHoriz = LucideIcons.ellipsis;
  static const IconData personAddAlt1 = LucideIcons.userPlus;
  static const IconData playArrow = LucideIcons.play;
  static const IconData playCircleOutline = LucideIcons.play;
  static const IconData refresh = LucideIcons.refreshCw;
  static const IconData search = LucideIcons.search;
  static const IconData searchOff = LucideIcons.searchX;
  static const IconData settings = LucideIcons.settings;
  static const IconData shieldCheck = LucideIcons.shieldCheck;
  static const IconData slidersHorizontal = LucideIcons.slidersHorizontal;
  static const IconData skipNext = LucideIcons.skipForward;
  static const IconData skipPrevious = LucideIcons.skipBack;
  static const IconData star = LucideIcons.star;
  static const IconData travelExplore = LucideIcons.compass;
  static const IconData users = LucideIcons.users;
  static const IconData viewAgenda = LucideIcons.rows3;
  static const IconData heart = LucideIcons.heart;
}
