"""For Popular

Revision ID: 8269963d14f5
Revises: 4e6a5f7b9c21
Create Date: 2026-04-17 03:12:39.734623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8269963d14f5'
down_revision: Union[str, Sequence[str], None] = '4e6a5f7b9c21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comics', sa.Column('popular_feed_batch_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('comics', sa.Column('popular_feed_page', sa.Integer(), nullable=True))
    op.add_column('comics', sa.Column('popular_feed_position', sa.Integer(), nullable=True))
    op.create_index('ix_comics_popular_feed_order', 'comics', ['popular_feed_batch_at', 'popular_feed_page', 'popular_feed_position'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_comics_popular_feed_order', table_name='comics')
    op.drop_column('comics', 'popular_feed_position')
    op.drop_column('comics', 'popular_feed_page')
    op.drop_column('comics', 'popular_feed_batch_at')
    # ### end Alembic commands ###
