"""Make slug composite unique with source_name

Revision ID: 8fdd0234a2df
Revises: d4d08a1805be
Create Date: 2026-04-13 18:56:02.932712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fdd0234a2df'
down_revision: Union[str, Sequence[str], None] = 'd4d08a1805be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comics_slug'), table_name='comics')
    op.create_index(op.f('ix_comics_slug'), 'comics', ['slug'], unique=False)
    op.create_unique_constraint('uq_source_slug', 'comics', ['source_name', 'slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_source_slug', 'comics', type_='unique')
    op.drop_index(op.f('ix_comics_slug'), table_name='comics')
    op.create_index(op.f('ix_comics_slug'), 'comics', ['slug'], unique=True)
    # ### end Alembic commands ###
