"""add_unique_constraint_chapter

Revision ID: d4d08a1805be
Revises: bfb2f5e6e046
Create Date: 2026-04-11 16:04:22.935925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4d08a1805be'
down_revision: Union[str, Sequence[str], None] = 'bfb2f5e6e046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_comic_chapter', 'chapters', ['comic_id', 'chapter_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_comic_chapter', 'chapters', type_='unique')
    # ### end Alembic commands ###
